version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
        - image: circleci/golang
    steps:
      - checkout

      - run:
          command:
            make test
workflows:
  version: 2
  # runs on feature branch commits
  test:
    jobs:
      - test
