version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
        - image: circleci/golang:1.11-node
    environment:
        - GOPATH: /home/circleci/repo/vendor:/home/circleci/repo/src/go
    steps:
      - checkout

      - run:
          command:
            npm install

      - run:
          command:
            mkdir /home/circleci/repo/vendor/bin
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - run:
          command:
              dep ensure

      - run:
          command:
            make test

workflows:
  version: 2
  # runs on feature branch commits
  test:
    jobs:
      - test
