version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
        - image: circleci/golang:1.11-node
    steps:
      - checkout

      - run:
          command:
            npm install

      - run:
          command:
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - run:
          command:
              dep ensure

      - run:
          command:
            make test

workflows:
  version: 2
  # runs on feature branch commits
  test:
    jobs:
      - test
