---
kind: Service
apiVersion: v1
metadata:
  name: cdots-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: cdots
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdots
  labels:
    app: cdots
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cdots
  template:
    metadata:
      labels:
        app: cdots
    spec:
      imagePullSecrets:
      - name: jwixel-docker-secret
      containers:
      - name: cdots
        image: jessewiles/cdots:0.0.15-rc0
        env:
        - name: CDOTS_MONGO_HOST
          value: "mongo-mongodb.mongo.svc.cluster.local"
        - name: CDOTS_MONGO_PORT
          value: "27017"
        - name: CDOTS_MONGO_USER
          value: "<REDACTED>"
        - name: CDOTS_MONGO_PASSWORD
          value: "<REDACTED>"
        ports:
        - containerPort: 8080
