apiVersion: v1
kind: Service
metadata:
  name: cdots-service
  namespace: cdots
spec:
  selector:
    app: cdots
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdots-deployment
  namespace: cdots
  labels:
    app: cdots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdots
  template:
    metadata:
      labels:
        app: cdots
    spec:
      containers:
      - name: cdots
        image: jessewiles/cdots:0.1.2-rc7
        ports:
        - containerPort: 8080
